[2025-10-02T01:26:05.973+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-02T01:26:05.978+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sentiment140_end2end_single.run_eda_and_clean manual__2025-10-02T01:05:24.833723+00:00 [queued]>
[2025-10-02T01:26:05.980+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sentiment140_end2end_single.run_eda_and_clean manual__2025-10-02T01:05:24.833723+00:00 [queued]>
[2025-10-02T01:26:05.981+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-10-02T01:26:05.984+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_eda_and_clean> on 2025-10-02 01:05:24.833723+00:00
[2025-10-02T01:26:05.993+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=6810) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-02T01:26:05.989+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sentiment140_end2end_single', 'run_eda_and_clean', 'manual__2025-10-02T01:05:24.833723+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/edaproject.py', '--cfg-path', '/tmp/tmpjhz_jwob']
[2025-10-02T01:26:05.994+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask run_eda_and_clean
[2025-10-02T01:26:05.994+0000] {standard_task_runner.py:63} INFO - Started process 6813 to run task
[2025-10-02T01:26:06.019+0000] {task_command.py:426} INFO - Running <TaskInstance: sentiment140_end2end_single.run_eda_and_clean manual__2025-10-02T01:05:24.833723+00:00 [running]> on host 619c97ee2164
[2025-10-02T01:26:06.046+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sentiment140_end2end_single' AIRFLOW_CTX_TASK_ID='run_eda_and_clean' AIRFLOW_CTX_EXECUTION_DATE='2025-10-02T01:05:24.833723+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-02T01:05:24.833723+00:00'
[2025-10-02T01:26:06.046+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-02T01:26:06.060+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-02T01:26:06.060+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/edaproject.py", line 113, in _run_eda_and_clean
    chunk_iter = pd.read_csv(csv_path, encoding="latin-1", header=None, names=COL_NAMES,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 718, in get_handle
    ioargs = _get_filepath_or_buffer(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 460, in _get_filepath_or_buffer
    raise ValueError(msg)
ValueError: Invalid file path or buffer object type: <class 'NoneType'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/edaproject.py", line 118, in _run_eda_and_clean
    chunk_iter = pd.read_csv(csv_path, encoding="latin-1", header=None, names=COL_NAMES,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 718, in get_handle
    ioargs = _get_filepath_or_buffer(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 460, in _get_filepath_or_buffer
    raise ValueError(msg)
ValueError: Invalid file path or buffer object type: <class 'NoneType'>
[2025-10-02T01:26:06.065+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=sentiment140_end2end_single, task_id=run_eda_and_clean, run_id=manual__2025-10-02T01:05:24.833723+00:00, execution_date=20251002T010524, start_date=20251002T012605, end_date=20251002T012606
[2025-10-02T01:26:06.068+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 8 for task run_eda_and_clean (Invalid file path or buffer object type: <class 'NoneType'>; 6813)
[2025-10-02T01:26:06.094+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-02T01:26:06.099+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1296 AirflowProviderDeprecationWarning: Call to deprecated class SnowflakeOperator. (This class is deprecated. Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`. Also, you can provide `hook_params={'warehouse': <warehouse>, 'database': <database>, 'role': <role>, 'schema': <schema>, 'authenticator': <authenticator>,'session_parameters': <session_parameters>}`.)
[2025-10-02T01:26:06.103+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-02T01:26:06.104+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
